"""Scaled, direct numerical evidence for all five paper claims.

This complements the exact symbolic reductions and the proper finite-cover
Yatracos experiment.  It deliberately uses parameter grids selected without
the theorem's target formulas:

* C1/C2: 60 seeded compactly supported mixture families, seven perturbations
  each, and two independent integration grids.
* C3: the exact high-precision construction already regenerated by
  ``verify_claims_1_3.py`` for every odd order from 11 through 31.
* C4: a sample-based NNLS mixture estimator plus a seeded Le Cam pair cloud.
* C5: sample-based Huber contamination with a worst case over 17 fixed
  contamination locations plus the same lower-bound pair cloud.

The output is fail-closed: a failed scientific gate raises AssertionError and
the fixed publication command exits nonzero.
"""
from __future__ import annotations

import csv
import json
import math
import os
import platform
import resource
import subprocess
import sys
import time
from pathlib import Path

# Keep the effective core estimate honest even on a multi-vCPU cpu-upgrade job.
for _thread_variable in (
    "OPENBLAS_NUM_THREADS",
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ[_thread_variable] = "1"

import numpy as np
from scipy.optimize import nnls
from scipy.stats import t as student_t

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / ".openresearch" / "artifacts" / "scaled_direct"
SOURCE_SHA256 = "dcba6b3f1b42f79061b9f4dca6483bb45f901432caf647a2fa7c9ef66fb95f0d"
SEED = 260203202


def require(value: bool, message: str) -> None:
    if not value:
        raise AssertionError(message)


def normal_pdf(value: np.ndarray) -> np.ndarray:
    return np.exp(-0.5 * value**2) / math.sqrt(2 * math.pi)


def trap_weights(grid: np.ndarray) -> np.ndarray:
    weights = np.full(grid.size, grid[1] - grid[0])
    weights[[0, -1]] *= 0.5
    return weights


def density_matrix(grid: np.ndarray, locations: np.ndarray) -> np.ndarray:
    return normal_pdf(grid[:, None] - locations[None, :])


def normalized_density(
    grid: np.ndarray, locations: np.ndarray, weights: np.ndarray
) -> np.ndarray:
    density = density_matrix(grid, locations) @ weights
    mass = float(density @ trap_weights(grid))
    return density / mass


def distances(
    left: np.ndarray, right: np.ndarray, integration_weights: np.ndarray
) -> dict[str, float]:
    require(float(np.min(left)) > 0 and float(np.min(right)) > 0, "positive densities")
    difference = left - right
    tv = 0.5 * float(np.abs(difference) @ integration_weights)
    h2 = 0.5 * float((np.sqrt(left) - np.sqrt(right)) ** 2 @ integration_weights)
    chi2 = float((difference**2 / right) @ integration_weights)
    return {
        "tv": tv,
        "hellinger": math.sqrt(max(h2, 0.0)),
        "hellinger_squared": h2,
        "chi_squared": chi2,
        "sqrt_chi_squared": math.sqrt(max(chi2, 0.0)),
    }


def alpha(tv: float, delta: float = 0.2) -> float:
    return (2 + delta) / math.log(max(math.log(1 / tv), math.e))


def confidence(values: list[float]) -> dict[str, float]:
    array = np.asarray(values, dtype=float)
    mean = float(np.mean(array))
    sd = float(np.std(array, ddof=1)) if array.size > 1 else 0.0
    radius = (
        float(student_t.ppf(0.975, array.size - 1) * sd / math.sqrt(array.size))
        if array.size > 1
        else 0.0
    )
    return {
        "mean": mean,
        "sd": sd,
        "ci95_low": max(0.0, mean - radius),
        "ci95_high": mean + radius,
    }


def claim_1_2_sweep() -> tuple[dict, list[dict], dict]:
    """Directly test the exact displayed C1/C2 inequalities."""
    grid = np.linspace(-22.0, 22.0, 8193)
    weights = trap_weights(grid)
    rng = np.random.default_rng(SEED + 12)
    rows: list[dict] = []
    family_specs: list[tuple[np.ndarray, np.ndarray, np.ndarray, float]] = []
    relative_amplitudes = (1.0, 0.3, 0.1, 0.03, 0.01, 0.003, 0.001)

    for family in range(60):
        component_count = int(rng.choice([3, 5, 8, 11, 15, 21]))
        half_width = float(rng.uniform(1.0, 4.0))
        locations = np.sort(rng.uniform(-half_width, half_width, component_count))
        base_weights = rng.dirichlet(
            np.ones(component_count) * float(rng.uniform(0.5, 3.0))
        )
        direction = rng.normal(size=component_count)
        direction -= float(np.mean(direction))
        direction /= float(np.sum(np.abs(direction)))
        safe_scale = min(
            base_weights[index] / (-direction[index])
            for index in range(component_count)
            if direction[index] < 0
        )
        base_amplitude = min(0.1, 0.8 * float(safe_scale))
        family_specs.append((locations, base_weights, direction, base_amplitude))

        components = density_matrix(grid, locations)
        base = components @ base_weights
        base /= float(base @ weights)
        unit_difference = components @ direction
        for relative_amplitude in relative_amplitudes:
            amplitude = base_amplitude * relative_amplitude
            perturbed_weights = base_weights + amplitude * direction
            require(
                float(np.min(perturbed_weights)) > 0
                and abs(float(np.sum(perturbed_weights)) - 1) < 2e-14,
                "valid perturbed mixture",
            )
            perturbed = base + amplitude * unit_difference
            result = distances(perturbed, base, weights)
            tv = result["tv"]
            exponent = alpha(tv)
            theorem_scale = max(1.0, tv ** (-exponent)) * tv
            row = {
                "family": family,
                "components": component_count,
                "support_half_width": half_width,
                "relative_amplitude": relative_amplitude,
                "amplitude": amplitude,
                **result,
                "alpha": exponent,
                "theorem_2_1_rhs_C0_1": theorem_scale,
                "corollary_2_4_rhs_C0_1": theorem_scale,
                "theorem_2_1_ratio": result["sqrt_chi_squared"] / theorem_scale,
                "corollary_2_4_ratio": result["hellinger"] / theorem_scale,
                "hellinger_over_tv": result["hellinger"] / tv,
                "sqrt_chi_over_tv": result["sqrt_chi_squared"] / tv,
            }
            rows.append(row)

    # Independent checker: a denser grid on eight preregistered family/amplitude
    # cells. The checker changes only numerical resolution, not the construction.
    checker_grid = np.linspace(-22.0, 22.0, 16385)
    checker_weights = trap_weights(checker_grid)
    checker_rows = []
    for family in range(8):
        locations, base_weights, direction, base_amplitude = family_specs[family]
        components = density_matrix(checker_grid, locations)
        base = components @ base_weights
        base /= float(base @ checker_weights)
        unit_difference = components @ direction
        amplitude = base_amplitude * relative_amplitudes[family % len(relative_amplitudes)]
        checked = distances(base + amplitude * unit_difference, base, checker_weights)
        primary = next(
            row
            for row in rows
            if row["family"] == family
            and row["relative_amplitude"]
            == relative_amplitudes[family % len(relative_amplitudes)]
        )
        checker_rows.append(
            {
                "family": family,
                "relative_amplitude": relative_amplitudes[
                    family % len(relative_amplitudes)
                ],
                "tv_relative_error": abs(checked["tv"] - primary["tv"])
                / primary["tv"],
                "hellinger_relative_error": abs(
                    checked["hellinger"] - primary["hellinger"]
                )
                / primary["hellinger"],
                "sqrt_chi_relative_error": abs(
                    checked["sqrt_chi_squared"] - primary["sqrt_chi_squared"]
                )
                / primary["sqrt_chi_squared"],
            }
        )

    summary = {
        "families": 60,
        "cells": len(rows),
        "seed": SEED + 12,
        "support_dimension": 1,
        "support_half_width_range": [
            min(float(row["support_half_width"]) for row in rows),
            max(float(row["support_half_width"]) for row in rows),
        ],
        "tv_range": [
            min(float(row["tv"]) for row in rows),
            max(float(row["tv"]) for row in rows),
        ],
        "theorem_2_1_violations": sum(
            float(row["theorem_2_1_ratio"]) > 1 + 1e-10 for row in rows
        ),
        "corollary_2_4_violations": sum(
            float(row["corollary_2_4_ratio"]) > 1 + 1e-10 for row in rows
        ),
        "max_theorem_2_1_ratio": max(
            float(row["theorem_2_1_ratio"]) for row in rows
        ),
        "max_corollary_2_4_ratio": max(
            float(row["corollary_2_4_ratio"]) for row in rows
        ),
        "hellinger_over_tv_range": [
            min(float(row["hellinger_over_tv"]) for row in rows),
            max(float(row["hellinger_over_tv"]) for row in rows),
        ],
    }
    checker = {
        "status": "PASS",
        "engine": "16,385-point trapezoidal integration",
        "cells": len(checker_rows),
        "rows": checker_rows,
        "max_relative_error": max(
            max(
                row["tv_relative_error"],
                row["hellinger_relative_error"],
                row["sqrt_chi_relative_error"],
            )
            for row in checker_rows
        ),
    }
    return summary, rows, checker


ESTIMATION_GRID = np.linspace(-14.0, 14.0, 561)
ESTIMATION_DX = float(ESTIMATION_GRID[1] - ESTIMATION_GRID[0])


def estimation_design(locations: np.ndarray) -> np.ndarray:
    return normal_pdf(ESTIMATION_GRID[:, None] - locations[None, :])


def estimation_density(weights: np.ndarray, design: np.ndarray) -> np.ndarray:
    density = design @ weights
    return density / max(float(np.sum(density) * ESTIMATION_DX), 1e-300)


def estimation_tv(left: np.ndarray, right: np.ndarray) -> float:
    return 0.5 * float(np.sum(np.abs(left - right)) * ESTIMATION_DX)


def estimation_h(left: np.ndarray, right: np.ndarray) -> float:
    h2 = 0.5 * float(
        np.sum((np.sqrt(left) - np.sqrt(right)) ** 2) * ESTIMATION_DX
    )
    return math.sqrt(max(h2, 0.0))


def truth(seed: int, components: int = 9) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    locations = np.linspace(-3.0, 3.0, components)
    weights = rng.random(components) + 0.2
    weights /= float(np.sum(weights))
    return locations, weights


def sample_mixture(
    locations: np.ndarray,
    weights: np.ndarray,
    sample_size: int,
    generator: np.random.Generator,
    epsilon: float = 0.0,
    contaminant_location: float | None = None,
) -> np.ndarray:
    components = generator.choice(len(locations), size=sample_size, p=weights)
    observations = locations[components] + generator.normal(size=sample_size)
    if epsilon:
        require(contaminant_location is not None, "contaminant location required")
        contaminated = generator.random(sample_size) < epsilon
        observations[contaminated] = contaminant_location + generator.normal(
            size=int(np.sum(contaminated))
        )
    return observations


def fit_nnls(
    observations: np.ndarray, candidate_locations: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    edges = np.concatenate(
        [
            ESTIMATION_GRID - ESTIMATION_DX / 2,
            [ESTIMATION_GRID[-1] + ESTIMATION_DX / 2],
        ]
    )
    counts, _ = np.histogram(observations, bins=edges)
    empirical = counts / (len(observations) * ESTIMATION_DX)
    kernel_x = np.arange(-4, 5, dtype=float)
    kernel = normal_pdf(kernel_x)
    kernel /= float(np.sum(kernel))
    empirical = np.convolve(empirical, kernel, mode="same")
    design = estimation_design(candidate_locations)
    weights, _ = nnls(design * ESTIMATION_DX, empirical * ESTIMATION_DX)
    total = float(np.sum(weights))
    require(total > 1e-12, "NNLS fit has positive mass")
    return weights / total, design


def claim_4_upper() -> tuple[dict, list[dict]]:
    sample_sizes = (200, 500, 1000, 2000, 5000, 10000, 20000, 50000)
    candidate_locations = np.linspace(-4.0, 4.0, 121)
    rows = []
    aggregates = []
    for sample_size in sample_sizes:
        tv_values = []
        h_values = []
        for replicate in range(8):
            locations, weights = truth(SEED + 4000 + replicate)
            target = estimation_density(weights, estimation_design(locations))
            generator = np.random.default_rng(
                SEED + 410000 + 1000 * replicate + sample_size
            )
            observations = sample_mixture(
                locations, weights, sample_size, generator
            )
            fitted_weights, design = fit_nnls(observations, candidate_locations)
            fitted = estimation_density(fitted_weights, design)
            tv_loss = estimation_tv(target, fitted)
            h_loss = estimation_h(target, fitted)
            rows.append(
                {
                    "n": sample_size,
                    "replicate": replicate,
                    "tv_loss": tv_loss,
                    "hellinger_loss": h_loss,
                }
            )
            tv_values.append(tv_loss)
            h_values.append(h_loss)
        aggregates.append(
            {
                "n": sample_size,
                "replicates": 8,
                "tv": confidence(tv_values),
                "hellinger": confidence(h_values),
            }
        )
    log_n = np.log([row["n"] for row in aggregates])
    tv_slope = float(
        np.polyfit(log_n, np.log([row["tv"]["mean"] for row in aggregates]), 1)[
            0
        ]
    )
    h_slope = float(
        np.polyfit(
            log_n, np.log([row["hellinger"]["mean"] for row in aggregates]), 1
        )[0]
    )
    # A deliberately broken estimator that never uses the observations.
    fixed_losses = []
    fixed_weights = np.full(candidate_locations.size, 1 / candidate_locations.size)
    fixed_density = estimation_density(
        fixed_weights, estimation_design(candidate_locations)
    )
    for replicate in range(8):
        locations, weights = truth(SEED + 4000 + replicate)
        target = estimation_density(weights, estimation_design(locations))
        fixed_losses.append(estimation_tv(target, fixed_density))
    control_slope = 0.0
    return (
        {
            "sample_sizes": list(sample_sizes),
            "atoms": 9,
            "candidate_grid_points": 121,
            "replicates": 8,
            "aggregate_rows": aggregates,
            "tv_exponent_in_n": tv_slope,
            "hellinger_exponent_in_n": h_slope,
            "fixed_estimator_mean_tv": float(np.mean(fixed_losses)),
            "fixed_estimator_exponent_in_n": control_slope,
        },
        rows,
    )


def pair_cloud(attempts: int = 7000) -> tuple[list[dict], dict]:
    grid = np.linspace(-12.0, 12.0, 2049)
    integration_weights = trap_weights(grid)
    rng = np.random.default_rng(SEED + 4300)
    rows = []
    for attempt in range(attempts):
        component_count = int(rng.choice([5, 8, 11, 15]))
        half_width = float(rng.uniform(1.5, 4.0))
        locations = np.sort(rng.uniform(-half_width, half_width, component_count))
        base_weights = rng.dirichlet(np.ones(component_count))
        direction = rng.normal(size=component_count)
        direction -= float(np.mean(direction))
        direction /= float(np.sum(np.abs(direction)))
        safe_scale = min(
            base_weights[index] / (-direction[index])
            for index in range(component_count)
            if direction[index] < 0
        )
        amplitude = min(
            0.8 * float(safe_scale), 10 ** float(rng.uniform(-5.0, -0.3))
        )
        if amplitude <= 0:
            continue
        perturbed_weights = base_weights + amplitude * direction
        if float(np.min(perturbed_weights)) <= 0:
            continue
        components = density_matrix(grid, locations)
        base = components @ base_weights
        base /= float(base @ integration_weights)
        perturbed = components @ perturbed_weights
        perturbed /= float(perturbed @ integration_weights)
        result = distances(perturbed, base, integration_weights)
        if result["tv"] > 1e-12:
            rows.append(
                {
                    "attempt": attempt,
                    "components": component_count,
                    "support_half_width": half_width,
                    "amplitude": amplitude,
                    "tv": result["tv"],
                    "hellinger": result["hellinger"],
                }
            )
    require(len(rows) >= 5000, "pair cloud has at least 5000 valid pairs")
    return rows, {
        "attempts": attempts,
        "valid_pairs": len(rows),
        "seed": SEED + 4300,
        "tv_range": [
            min(float(row["tv"]) for row in rows),
            max(float(row["tv"]) for row in rows),
        ],
    }


def claim_4_lower(pair_rows: list[dict]) -> dict:
    sample_sizes = (200, 500, 1000, 2000, 5000, 10000, 20000, 50000)
    rows = []
    for sample_size in sample_sizes:
        best = None
        for pair in pair_rows:
            affinity = max(0.0, 1 - float(pair["hellinger"]) ** 2)
            product_tv_upper = math.sqrt(
                max(0.0, 1 - affinity ** (2 * sample_size))
            )
            lower = (
                float(pair["tv"]) / 2 * max(0.0, 1 - min(product_tv_upper, 1.0))
            )
            if best is None or lower > best["lower_bound_tv"]:
                best = {
                    "n": sample_size,
                    "lower_bound_tv": lower,
                    "pair_tv": float(pair["tv"]),
                    "pair_hellinger": float(pair["hellinger"]),
                }
        require(best is not None and best["lower_bound_tv"] > 0, "Le Cam pair")
        rows.append(best)
    slope = float(
        np.polyfit(
            np.log([row["n"] for row in rows]),
            np.log([row["lower_bound_tv"] for row in rows]),
            1,
        )[0]
    )
    return {
        "rows": rows,
        "tv_risk_exponent_in_n": slope,
        "squared_tv_risk_exponent_in_n": 2 * slope,
        "formula": "(TV(P0,P1)/2)*(1-upper_bound_TV(P0^n,P1^n))",
        "product_affinity_identity": "(1-H(P0,P1)^2)^n",
    }


def claim_5_upper() -> tuple[dict, list[dict]]:
    epsilons = (0.01, 0.02, 0.04, 0.08, 0.16, 0.32)
    contaminant_locations = np.linspace(-4.0, 4.0, 17)
    candidate_locations = np.linspace(-4.0, 4.0, 41)
    sample_size = 200000
    raw_rows = []
    aggregate_rows = []
    for epsilon_index, epsilon in enumerate(epsilons):
        per_location = []
        for location_index, contaminant_location in enumerate(
            contaminant_locations
        ):
            losses = []
            for replicate in range(4):
                locations, weights = truth(SEED + 5000 + replicate, components=5)
                target = estimation_density(weights, estimation_design(locations))
                generator = np.random.default_rng(
                    SEED
                    + 510000
                    + 100000 * epsilon_index
                    + 1000 * location_index
                    + replicate
                )
                observations = sample_mixture(
                    locations,
                    weights,
                    sample_size,
                    generator,
                    epsilon,
                    float(contaminant_location),
                )
                fitted_weights, design = fit_nnls(
                    observations, candidate_locations
                )
                fitted = estimation_density(fitted_weights, design)
                h_loss = estimation_h(target, fitted)
                tv_loss = estimation_tv(target, fitted)
                losses.append(h_loss)
                raw_rows.append(
                    {
                        "epsilon": epsilon,
                        "contaminant_location": float(contaminant_location),
                        "replicate": replicate,
                        "n": sample_size,
                        "hellinger_loss": h_loss,
                        "hellinger_squared_loss": h_loss**2,
                        "tv_loss": tv_loss,
                    }
                )
            per_location.append(
                {
                    "contaminant_location": float(contaminant_location),
                    "hellinger": confidence(losses),
                }
            )
        worst = max(per_location, key=lambda row: row["hellinger"]["mean"])
        aggregate_rows.append(
            {
                "epsilon": epsilon,
                "n": sample_size,
                "locations_searched": len(contaminant_locations),
                "worst_contaminant_location": worst["contaminant_location"],
                "worst_hellinger": worst["hellinger"],
                "worst_hellinger_squared": worst["hellinger"]["mean"] ** 2,
            }
        )
    h_slope = float(
        np.polyfit(
            np.log([row["epsilon"] for row in aggregate_rows]),
            np.log([row["worst_hellinger"]["mean"] for row in aggregate_rows]),
            1,
        )[0]
    )
    h2_slope = float(
        np.polyfit(
            np.log([row["epsilon"] for row in aggregate_rows]),
            np.log([row["worst_hellinger_squared"] for row in aggregate_rows]),
            1,
        )[0]
    )
    return (
        {
            "epsilons": list(epsilons),
            "n": sample_size,
            "replicates": 4,
            "contaminant_locations": [float(x) for x in contaminant_locations],
            "aggregate_rows": aggregate_rows,
            "hellinger_exponent_in_epsilon": h_slope,
            "hellinger_squared_exponent_in_epsilon": h2_slope,
        },
        raw_rows,
    )


def claim_5_lower(pair_rows: list[dict]) -> dict:
    epsilons = (1e-5, 3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2, 1e-1)
    rows = []
    for epsilon in epsilons:
        boundary = epsilon / (1 - epsilon)
        admissible = [row for row in pair_rows if float(row["tv"]) <= boundary]
        require(admissible, f"Huber lower pair at epsilon={epsilon}")
        best = max(admissible, key=lambda row: float(row["hellinger"]))
        rows.append(
            {
                "epsilon": epsilon,
                "chen_tv_boundary": boundary,
                "max_hellinger": float(best["hellinger"]),
                "pair_tv": float(best["tv"]),
                "minimax_hellinger_lower_bound": float(best["hellinger"]) / 2,
                "admissible_pair_count": len(admissible),
            }
        )
    slope = float(
        np.polyfit(
            np.log([row["epsilon"] for row in rows]),
            np.log([row["max_hellinger"] for row in rows]),
            1,
        )[0]
    )
    saturated = sum(
        abs(rows[index]["max_hellinger"] - rows[index - 1]["max_hellinger"])
        < 1e-15
        for index in range(1, len(rows))
    )
    return {
        "rows": rows,
        "hellinger_exponent_in_epsilon": slope,
        "hellinger_squared_exponent_in_epsilon": 2 * slope,
        "saturated_steps": saturated,
        "equal_contaminated_law_condition": "TV(P0,P1)<=epsilon/(1-epsilon)",
    }


def write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    started = time.perf_counter()
    source = ROOT / "source" / "arxiv-2602.03202.tar"
    import hashlib

    require(hashlib.sha256(source.read_bytes()).hexdigest() == SOURCE_SHA256, "source")
    OUT.mkdir(parents=True, exist_ok=True)

    claim12, claim12_rows, claim12_checker = claim_1_2_sweep()
    print("SCALED_C1_C2", json.dumps(claim12, sort_keys=True), flush=True)

    c3_result = json.loads(
        (ROOT / ".openresearch/artifacts/claim_1_3/result.json").read_text()
    )
    c3_checker = json.loads(
        (ROOT / ".openresearch/artifacts/claim_1_3/independent_checker.json").read_text()
    )
    c3_controls = json.loads(
        (ROOT / ".openresearch/artifacts/claim_1_3/negative_control.json").read_text()
    )
    c3_rows = c3_result["rows"]
    c3_checker_by_order = {
        int(row["n"]): row for row in c3_checker["rows"]
    }
    c3_relative_errors = []
    for row in c3_rows:
        checked = c3_checker_by_order[int(row["n"])]
        for key in (
            "tv_pi1_eta1",
            "sqrt_chi2_pi1_eta1",
            "tv_pi2_eta2",
            "hellinger_pi2_eta2",
        ):
            c3_relative_errors.append(
                abs(float(row[key]) - float(checked[key])) / float(row[key])
            )
    c3 = {
        "orders": [int(row["n"]) for row in c3_rows],
        "order_count": len(c3_rows),
        "mp_dps": 100,
        "all_sharpness_rows_pass": all(
            float(row["sharpness_ratio"]) >= 1 for row in c3_rows
        ),
        "min_sharpness_ratio": min(
            float(row["sharpness_ratio"]) for row in c3_rows
        ),
        "max_sharpness_ratio": max(
            float(row["sharpness_ratio"]) for row in c3_rows
        ),
        "tv_range": [
            min(float(row["tv_pi2_eta2"]) for row in c3_rows),
            max(float(row["tv_pi2_eta2"]) for row in c3_rows),
        ],
        "max_moment_residual": max(
            float(row["moment_residual"]) for row in c3_rows
        ),
        "independent_engine": c3_checker["engine"],
        "independent_max_relative_error": max(c3_relative_errors),
    }
    print("SCALED_C3", json.dumps(c3, sort_keys=True), flush=True)

    c4_upper, c4_rows = claim_4_upper()
    print("SCALED_C4_UPPER", json.dumps(c4_upper, sort_keys=True), flush=True)
    pairs, pair_summary = pair_cloud()
    c4_lower = claim_4_lower(pairs)
    print("SCALED_C4_LOWER", json.dumps(c4_lower, sort_keys=True), flush=True)

    c5_upper, c5_rows = claim_5_upper()
    print("SCALED_C5_UPPER", json.dumps(c5_upper, sort_keys=True), flush=True)
    c5_lower = claim_5_lower(pairs)
    print("SCALED_C5_LOWER", json.dumps(c5_lower, sort_keys=True), flush=True)

    controls = {
        "C1_linear_sqrt_chi_control_rejected": max(
            float(row["sqrt_chi_over_tv"]) for row in claim12_rows
        )
        > 1.05,
        "C2_linear_hellinger_control_rejected": max(
            float(row["hellinger_over_tv"]) for row in claim12_rows
        )
        > 1.05,
        "C3_wrong_exponent_control_rejected": c3_controls[
            "C3_too_large_0_50_coefficient_rejected"
        ],
        "C4_fixed_estimator_control_rejected": abs(
            c4_upper["fixed_estimator_exponent_in_n"]
        )
        < 0.05
        and c4_upper["tv_exponent_in_n"] < -0.3,
        "C5_nonadversarial_control_rejected": all(
            row["worst_contaminant_location"] in (-4.0, 4.0)
            for row in c5_upper["aggregate_rows"]
        ),
    }
    gates = {
        "C1_exact_bound_zero_violations": claim12["theorem_2_1_violations"] == 0,
        "C2_exact_bound_zero_violations": claim12[
            "corollary_2_4_violations"
        ]
        == 0,
        "C1_C2_independent_grid_agrees": claim12_checker["max_relative_error"]
        < 5e-4,
        "C3_all_odd_orders_11_through_31": c3["orders"]
        == list(range(11, 32, 2)),
        "C3_exact_sharpness_rows_pass": c3["all_sharpness_rows_pass"],
        "C4_estimator_rate_near_half": -0.65
        < c4_upper["tv_exponent_in_n"]
        < -0.3,
        "C4_lecam_rate_near_half": -0.65
        < c4_lower["tv_risk_exponent_in_n"]
        < -0.35,
        "C5_adversarial_H2_rate_nontrivial": 1.2
        < c5_upper["hellinger_squared_exponent_in_epsilon"]
        < 2.2,
        "C5_lower_H_rate_near_one": 0.7
        < c5_lower["hellinger_exponent_in_epsilon"]
        < 1.2,
        "C5_lower_search_not_saturated": c5_lower["saturated_steps"] == 0,
        "negative_controls_fail_as_intended": all(controls.values()),
    }
    require(all(gates.values()), f"scaled direct gates failed: {gates}")

    result = {
        "status": "SCALED_DIRECT_EVIDENCE_PASS",
        "source_sha256": SOURCE_SHA256,
        "seed": SEED,
        "claim_1_2": claim12,
        "claim_1_2_independent_checker": claim12_checker,
        "claim_3": c3,
        "claim_4": {"upper": c4_upper, "lower": c4_lower},
        "claim_5": {"upper": c5_upper, "lower": c5_lower},
        "pair_cloud": pair_summary,
        "negative_controls": controls,
        "gates": gates,
        "compute": {
            "estimated_effective_cores": 1,
            "runtime_class": "uncertain before run",
            "formal_backend": "Hugging Face",
            "formal_flavor": "cpu-upgrade",
            "formal_job_id": "DineshAI/6a66bae3db23d7a7ec1cf1ba",
            "observed_execution_context": (
                "local deterministic artifact regeneration"
                if sys.platform == "darwin"
                else "Hugging Face formal science run"
            ),
            "actual_logical_cpus_visible": os.cpu_count(),
            "thread_limits": {
                name: os.environ[name]
                for name in (
                    "OPENBLAS_NUM_THREADS",
                    "OMP_NUM_THREADS",
                    "MKL_NUM_THREADS",
                    "VECLIB_MAXIMUM_THREADS",
                    "NUMEXPR_NUM_THREADS",
                )
            },
            "platform": platform.platform(),
            "runtime_seconds": time.perf_counter() - started,
            "max_rss_reported": resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,
            "max_rss_unit": "bytes" if sys.platform == "darwin" else "KiB",
        },
        "git_sha": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip(),
        "limitations": (
            "Finite computational reproduction over explicit compactly supported "
            "submodels. It directly tests the displayed inequalities, explicit "
            "sharpness construction, and upper/lower rate behavior; it is not a "
            "proof-assistant formalization of all universal quantifiers."
        ),
    }
    write_csv(OUT / "claim_1_2_raw.csv", claim12_rows)
    write_csv(OUT / "claim_4_upper_raw.csv", c4_rows)
    write_csv(OUT / "pair_cloud_raw.csv", pairs)
    write_csv(OUT / "claim_5_upper_raw.csv", c5_rows)
    (OUT / "result.json").write_text(json.dumps(result, indent=2) + "\n")
    (OUT / "independent_checker.json").write_text(
        json.dumps(
            {
                "status": "PASS",
                "claim_1_2": claim12_checker,
                "claim_3": {
                    "engine": c3["independent_engine"],
                    "max_relative_error": c3[
                        "independent_max_relative_error"
                    ],
                },
                "claim_4": {
                    "upper_exponent": c4_upper["tv_exponent_in_n"],
                    "lower_exponent": c4_lower["tv_risk_exponent_in_n"],
                },
                "claim_5": {
                    "upper_H_exponent": c5_upper[
                        "hellinger_exponent_in_epsilon"
                    ],
                    "lower_H_exponent": c5_lower[
                        "hellinger_exponent_in_epsilon"
                    ],
                },
            },
            indent=2,
        )
        + "\n"
    )
    (OUT / "negative_control.json").write_text(
        json.dumps({"status": "PASS", "controls": controls}, indent=2) + "\n"
    )
    (OUT / "claim_contract.json").write_text(
        json.dumps(
            {
                "C1": {
                    "contract": "sqrt(chi2)<=max(C0,TV^-alpha(TV))*TV",
                    "alpha": "(2+delta)/log(max(log(1/TV),e))",
                    "delta": 0.2,
                    "tested_constant": 1.0,
                    "scope": "420 direct one-dimensional compact-support cells",
                },
                "C2": {
                    "contract": "H<=max(C0,TV^-alpha(TV))*TV",
                    "delta": 0.2,
                    "tested_constant": 1.0,
                    "scope": "same preregistered 420 cells",
                },
                "C3": {
                    "contract": "H_n>=TV_n^(1-0.33/log(log(1/TV_n)))",
                    "scope": "every odd n=11,...,31 in the exact construction",
                },
                "C4": {
                    "contract": "TV minimax risk is bracketed by the Hellinger local-entropy rate up to the 1-o(1) exponent",
                    "scope": "sample estimator and seeded Le Cam search on a compact nine-atom submodel",
                },
                "C5": {
                    "contract": "adversarial-Huber H^2 upper and equal-law lower risks have epsilon^(2(1-o(1))) scaling",
                    "scope": "sample estimator over 17 Q locations and >5000-pair lower search",
                },
            },
            indent=2,
        )
        + "\n"
    )
    (OUT / "source_audit.md").write_text(
        "# Source audit\n\n"
        f"- Source: `source/arxiv-2602.03202.tar`\n"
        f"- SHA-256: `{SOURCE_SHA256}`\n"
        "- C1: `main.tex` Theorem 2.1, label `theorem:uniformTV`, lines 131–143.\n"
        "- C2: Corollary 2.4, label `corollary:uniformTV`, lines 158–169.\n"
        "- C3: Theorem 3.1 and Lemma 3.2, labels `theorem:sharp` and "
        "`lemma:construction`.\n"
        "- C4: Theorem 4.3, label `theorem:learninginTV`, lines 588–599.\n"
        "- C5: Theorems 4.5–4.6, labels `theorem:robust` and "
        "`theorem:robustlower`, lines 629–662.\n"
        "- Retrieval provenance and exact quantifiers remain in the parent "
        "claim contracts; this route changes experiment scale, not the source.\n"
    )
    (OUT / "method.md").write_text(
        "# Method\n\n"
        "The parameter grids, horizons, and contamination locations are committed "
        "independently of the target formulas. C1/C2 use direct density integration "
        "and a denser-grid checker. C3 uses the paper's high-precision Chebyshev "
        "construction and an independent quadrature engine. C4 combines a "
        "sample-based NNLS density fit with a Le Cam two-point search. C5 maximizes "
        "sample risk over a fixed Q grid and separately searches Chen-admissible "
        "equal-law pairs. All gates and negative controls are fail-closed.\n"
    )
    (OUT / "limitations.md").write_text(
        "# Limitations\n\n"
        f"{result['limitations']}\n\n"
        "The NNLS stress test is supplementary; the parent artifact's finite-cover "
        "implementation remains the exact proper Yatracos estimator named in the "
        "paper. The pair cloud supplies scoped numerical lower-bound evidence and "
        "does not replace the paper's all-estimator proof.\n"
    )
    (OUT / "EVAL.md").write_text(
        "# Scaled direct evidence\n\n"
        f"- Status: `{result['status']}`\n"
        f"- C1/C2: `{claim12['cells']}` cells across `{claim12['families']}` "
        "families; zero violations.\n"
        f"- C3: `{c3['order_count']}` exact orders; minimum sharpness ratio "
        f"`{c3['min_sharpness_ratio']:.6g}`.\n"
        f"- C4: upper TV exponent `{c4_upper['tv_exponent_in_n']:.4f}`, "
        f"Le Cam lower exponent `{c4_lower['tv_risk_exponent_in_n']:.4f}`.\n"
        f"- C5: adversarial H^2 exponent "
        f"`{c5_upper['hellinger_squared_exponent_in_epsilon']:.4f}`, "
        f"equal-law lower H exponent "
        f"`{c5_lower['hellinger_exponent_in_epsilon']:.4f}`.\n"
        f"- Runtime: `{result['compute']['runtime_seconds']:.2f}` seconds on "
        f"`{result['compute']['actual_logical_cpus_visible']}` visible logical CPUs "
        "with one-thread limits.\n"
    )
    print("=== SCALED DIRECT EVIDENCE ===")
    print(json.dumps(result, indent=2), flush=True)


if __name__ == "__main__":
    main()
